type Range = { max: number; messages: string[] };

const RANGES: Range[] = [
  {
    max: 5,
    messages: [
      "faster than a camera shutter",
      "faster than a hummingbird's wingbeat",
      "quicker than a blink",
      "faster than most reflexes register",
      "faster than a shooting star streaks",
      "quicker than a champagne cork pops",
      "faster than a firefly's flash",
      "faster than a sneeze escapes",
      "faster than a dolphin surfaces for air",
      "quicker than a whip cracks",
      "faster than a magician's sleight of hand",
      "quicker than a papercut happens",
      "faster than a cat's ear twitches at a noise",
      "quicker than a match flares up",
      "faster than a pinball launches off the plunger",
      "quicker than a gecko's tongue snags its prey",
      "faster than a dragonfly changes direction mid-flight",
      "quicker than a soap bubble pops",
      "faster than a coin flip decides",
      "quicker than a thought becomes a whisper",
    ],
  },
  {
    max: 8,
    messages: [
      "about as long as a deep breath",
      "faster than most people tie their shoes",
      "about as long as a firm handshake",
      "quicker than reading this sentence",
      "quicker than a toast pops up",
      "about as long as a curious glance across a room",
      "quicker than most people say their own name",
      "about as long as a fridge light turning on",
      "quicker than a cat decides if it trusts you",
      "about as long as a rubber band snapping",
      "quicker than a ladybug unfolds its wings",
      "about as long as a phone notification buzz",
      "faster than most people remember a password",
      "about as long as a single gulp of water",
      "quicker than a mosquito whines past your ear",
      "about as long as a first impression forms",
    ],
  },
  {
    max: 12,
    messages: [
      "faster than most people read a sentence",
      "about as long as a microwave beep sequence",
      "quicker than finding WiFi password",
      "faster than a barista calls your name",
      "about as long as a proper sneeze fit",
      "quicker than most people type a short text",
      "about as long as it takes to say a tongue twister",
      "quicker than a free throw releases",
      "faster than most people mute a youtube ad",
      "about as long as an elevator door opens",
      "quicker than a camera timer beeps before the shot",
      "about as long as a single lightning bug glow",
      "quicker than a song's intro riff grabs you",
      "faster than a chef cracks an egg one-handed",
      "quicker than squaring a corner in a racing game",
    ],
  },
  {
    max: 18,
    messages: [
      "quicker than brewing an espresso shot",
      "faster than most elevator doors close",
      "about as long as a decent guitar riff",
      "quicker than parallel parking in one go",
      "faster than loading Instagram used to be",
      "about as long as a microwave counts down from fifteen",
      "faster than most people fold a t-shirt",
      "about as long as a held note in a power ballad",
      "quicker than a barista pours a latte art leaf",
      "about as long as a cat stretches in a sunbeam",
      "faster than a subway door closes after the chime",
      "about as long as a good yawn and stretch",
      "quicker than most people open a stubborn jar",
      "about as long as a short jog across an intersection",
      "faster than most people give a genuine compliment",
    ],
  },
  {
    max: 25,
    messages: [
      "faster than a London tube door closing",
      "about as long as a standing ovation start",
      "quicker than most people pick a Netflix show",
      "faster than a Formula 1 pit stop window",
      "about as long as the best part of a song",
      "about as long as a microwave counts down from twenty",
      "faster than a candle wick catches flame",
      "about as long as a hot air balloon burner blast",
      "quicker than most people pick a profile picture",
      "about as long as a held yoga breath",
      "faster than a traffic light turns green for you",
      "about as long as a plane's takeoff announcement",
      "quicker than a locksmith picks a simple lock",
      "about as long as a vaudeville bow",
      "faster than most people decide what to order",
    ],
  },
  {
    max: 35,
    messages: [
      "about as long as a perfect handshake",
      "faster than most people read a paragraph",
      "about as long as a news headline segment",
      "quicker than a microwave minute feels",
      "about as long as a dramatic film pause",
      "about as long as a skipped ad waits to disappear",
      "faster than a barista makes a simple coffee",
      "about as long as a cold start computer boot",
      "quicker than a meditative breath cycle",
      "about as long as getting a good photo of a cat",
      "faster than most people explain a dream",
      "about as long as a yo-yo reaches its bottom",
      "quicker than a blackjack hand plays out",
      "about as long as a firework fuse burns",
      "faster than most people match a sock from the laundry",
    ],
  },
  {
    max: 50,
    messages: [
      "faster than most elevator rides",
      "about as long as a great opening line",
      "quicker than most people find their keys",
      "about as long as the best film shots",
      "faster than most people choose a password",
      "about as long as a song's chorus and verse",
      "faster than a pop song intro fades in",
      "about as long as a crossing guard stops traffic",
      "faster than a short improv scene gets laughs",
      "about as long as a seagull steals a chip",
      "about as long as a single lap around a small parking lot",
      "faster than most people write a tweet they never post",
      "about as long as someone holds the door from across the hall",
      "quicker than a barista writes your name on a cup",
      "about as long as a cold engine turns over twice",
    ],
  },
  {
    max: 70,
    messages: [
      "about as long as a stoplight",
      "faster than most people make a decision",
      "about as long as a good chorus",
      "quicker than reading the first page of a book",
      "about as long as a spacecraft separation burn",
      "about as long as a subway stop dwell time",
      "quicker than a dream snippet fades after waking",
      "about as long as a street performer's whole trick",
      "about as long as a minute of deep breathing",
      "about as long as a slow elevator to the third floor",
      "quicker than most people find their ringing phone",
      "about as long as a bird splashes in a puddle",
      "faster than a tied shoelace comes undone mid-stride",
      "about as long as a one-minute song snippet",
      "quicker than most people unlock their phone",
    ],
  },
  {
    max: 90,
    messages: [
      "longer than a TikTok used to be",
      "about as long as a decent trailer",
      "roughly as long as a closing argument",
      "about the time it takes to forget why you walked in",
      "longer than most people's attention span online",
      "about as long as a short poem read aloud",
      "longer than a viral video recap",
      "about as long as untangling a headphone knot",
      "about as long as a hot towel treatment at the barber",
      "about the time it takes to draw a mustache on a photo",
      "longer than a quick shower when you're running late",
      "about as long as a song's bridge and final chorus",
      "roughly as long as a traffic light cycles through all three colors",
      "about the time it takes to convince yourself to get up",
      "longer than a motivational quote is supposed to last",
    ],
  },
  {
    max: 120,
    messages: [
      "about as long as a movie trailer",
      "longer than most ads you skip",
      "about as long as a strong coffee kick",
      "roughly the length of a perfect elevator pitch",
      "about as long as waiting for a delayed reply",
      "about as long as brushing your teeth properly",
      "longer than a pop song's first verse",
      "about as long as a plane taxiing to the runway",
      "roughly the time it takes to fold a fitted sheet",
      "about as long as a microwave bag of popcorn",
      "longer than most people hold a plank",
      "about as long as waiting for a photo to send",
      "about as long as a voicemail you actually listen to",
      "roughly the length of a stand-up comedian's opening minute",
      "about as long as a loading screen on a slow connection",
    ],
  },
  {
    max: Infinity,
    messages: [
      "even legends started somewhere",
      "every master was once a beginner",
      "the cube respects the attempt",
      "time is just a number. keep going",
      "Feliks Zemdegs didn't start fast either",
      "the cube has been waiting longer than a delayed bus",
      "you've been solving longer than most people keep a new year's resolution",
      "slower solves build faster intuition",
      "a minute forgotten is better than a cube left unsolved",
      "every second is its own little story",
      "patience is a puzzle too",
      "you're not slow, you're thorough",
      "the cube doesn't judge. it just turns",
      "you're faster than you were yesterday",
      "this is the part in the movie where the hero trains",
      "awkward silences are harder than this solve",
      "you're lapping everyone who hasn't started yet",
      "slow is smooth and smooth is fast",
      "every scramble is a new beginning",
      "persistence matters more than speed ever will",
    ],
  },
];

let lastShown: string | null = null;

export function getComparison(seconds: number): string {
  const range = RANGES.find((r) => seconds < r.max) ?? RANGES[RANGES.length - 1];
  const pool = range.messages.filter((m) => m !== lastShown);
  const choices = pool.length > 0 ? pool : range.messages;
  const pick = choices[Math.floor(Math.random() * choices.length)];
  lastShown = pick;
  return pick;
}
